var library = {
	theweeknd: {
		title: "The Weeknd",
		song1: {
			name: "Starboy",
			artist: "The Weeknd ft. Daft Punk",
			album: "Starboy",
			location: "lib/TheWeeknd/Starboy.mp3",
		},
		song2: {
			name: "Party Monster",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Party Monster.mp3",
		},
		song3: {
			name: "False Alarm",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/False Alarm.mp3",
		},
		song4: {
			name: "Reminder",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Reminder.mp3",
		},
		song5: {
			name: "Rockin'",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Rockin.mp3",
		},
		song6: {
			name: "Secrets",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Secrets.mp3",
		},
		song7: {
			name: "True Colors",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/True Colors.mp3",
		},
		song8: {
			name: "Stargirl Interlude",
			artist: "The Weeknd ft. Lana Del Rey",
			album: "Starboy",
			location: "lib/TheWeeknd/Stargirl Interlude.mp3",
		},
		song9: {
			name: "Sidewalks",
			artist: "The Weeknd ft. Kendrick Lamar",
			album: "Starboy",
			location: "lib/TheWeeknd/Sidewalks.mp3",
		},
		song10: {
			name: "Six Feet Under",
			artist: "The Weeknd ft. Future",
			album: "Starboy",
			location: "lib/TheWeeknd/Six Feet Under.mp3",
		},
		song11: {
			name: "Love to Lay",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Love To Lay.mp3",
		},
		song12: {
			name: "A Lonely Night",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/A Lonely Night.mp3",
		},
		song13: {
			name: "Attention",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Attention.mp3",
		},
		song14: {
			name: "Ordinary Life",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Ordinary Life.mp3",
		},
		song15: {
			name: "Nothing Without You",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Nothing Without You.mp3",
		},
		song16: {
			name: "All I Know",
			artist: "The Weeknd ft. Future",
			album: "Starboy",
			location: "lib/TheWeeknd/All I Know.mp3",
		},
		song17: {
			name: "Die For You",
			artist: "The Weeknd",
			album: "Starboy",
			location: "lib/TheWeeknd/Die For You.mp3",
		},
		song18: {
			name: "I Feel It Coming",
			artist: "The Weeknd ft. Daft Punk",
			album: "Starboy",
			location: "lib/TheWeeknd/I Feel It Coming.mp3",
		},
		song19: {
			name: "Tell Your Friends",
			artist: "The Weeknd",
			album: "Beauty Behind the Madness",
			location: "lib/TheWeeknd/Tell Your Friends.mp3",
		},
		song20: {
			name: "Often",
			artist: "The Weeknd",
			album: "Beauty Behind the Madness",
			location: "lib/TheWeeknd/Often.mp3",
		},
		song21: {
			name: "",
			artist: "The Weeknd",
			album: "Beauty Behind the Madness",
			location: "lib/TheWeeknd/",
		},
		song22: {
			name: "",
			artist: "The Weeknd",
			album: "Beauty Behind the Madness",
			location: "lib/TheWeeknd/",
		},
		song23: {
			name: "",
			artist: "The Weeknd",
			album: "Beauty Behind the Madness",
			location: "lib/TheWeeknd/",
		},
		song24: {
			name: "",
			artist: "The Weeknd",
			album: "Beauty Behind the Madness",
			location: "lib/TheWeeknd/",
		},
	},
	logic: {
		title: "Logic",
		song1: {
			name: "1-800-273-8255",
			artist: "Logic",
			album: "Everybody",
			location: "lib/Logic/1-800-273-8255.mp3",
		},
		song2: {
			name: "Flexicution",
			artist: "Logic",
			album: "Bobby Tarantino",
			location: "lib/Logic/Flexicution.mp3",
		},
		song3: {
			name: "Gang Related",
			artist: "Logic",
			album: "Under Pressure",
			location: "lib/Logic/Gang Related.mp3",
		},
	},

};